FROM python:3.12
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /workdir

COPY ./pyproject.toml ./uv.lock /workdir/

RUN uv sync --dev --no-install-project

ENV PATH="/workdir/.venv/bin:$PATH"
ENV PYTHONPATH=/workdir:${PYTHONPATH}
