"""make Session nullable

Revision ID: 909bd79e922d
Revises: 62ed393e6177
Create Date: 2024-10-13 23:55:36.521719+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "909bd79e922d"
down_revision: Union[str, None] = "62ed393e6177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apps", "auth_configs", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apps", "auth_configs", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    # ### end Alembic commands ###
