"""update App table

Revision ID: 62ed393e6177
Revises: a1c7e929bb76
Create Date: 2024-10-13 22:35:19.933615+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62ed393e6177"
down_revision: Union[str, None] = "a1c7e929bb76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("apps", sa.Column("server_url", sa.String(length=255), nullable=False))
    op.add_column("apps", sa.Column("auth_configs", sa.JSON(), nullable=False))
    op.alter_column(
        "apps",
        "provider",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_column("apps", "website")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "apps", sa.Column("website", sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "apps",
        "provider",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_column("apps", "auth_configs")
    op.drop_column("apps", "server_url")
    # ### end Alembic commands ###
