"""add enabled column for connected_accounts table

Revision ID: b1526374d41f
Revises: 909bd79e922d
Create Date: 2024-10-15 20:52:47.649872+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1526374d41f"
down_revision: Union[str, None] = "909bd79e922d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("connected_accounts", sa.Column("enabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("connected_accounts", "enabled")
    # ### end Alembic commands ###
