"""support authenticated api call

Revision ID: 65a19467ca3c
Revises:
Create Date: 2024-12-12 10:50:59.966485+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "65a19467ca3c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # create extension if not exists vector;
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("logo", sa.Text(), nullable=True),
        sa.Column("categories", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("visibility", sa.Enum("PUBLIC", "PRIVATE", name="visibility"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("security_schemes", sa.JSON(), nullable=False),
        sa.Column("embedding", Vector(dim=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auth_provider", sa.String(length=255), nullable=False),
        sa.Column("auth_user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("profile_picture", sa.Text(), nullable=True),
        sa.Column(
            "plan", sa.Enum("CUSTOM", "FREE", "PRO", "ENTERPRISE", name="plan"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_provider", "auth_user_id", name="uc_auth_provider_user"),
    )
    op.create_table(
        "functions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("visibility", sa.Enum("PUBLIC", "PRIVATE", name="visibility"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("protocol", sa.Enum("REST", name="protocol"), nullable=False),
        sa.Column("protocol_data", sa.JSON(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("embedding", Vector(dim=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("owner_organization_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "visibility_access", sa.Enum("PUBLIC", "PRIVATE", name="visibility"), nullable=False
        ),
        sa.Column("daily_quota_used", sa.Integer(), nullable=False),
        sa.Column(
            "daily_quota_reset_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total_quota_used", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(owner_user_id IS NOT NULL AND owner_organization_id IS NULL) OR (owner_user_id IS NULL AND owner_organization_id IS NOT NULL)",
            name="cc_project_owner",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("excluded_apps", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("excluded_functions", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_app_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column(
            "security_scheme",
            sa.Enum(
                "API_KEY",
                "HTTP_BASIC",
                "HTTP_BEARER",
                "OAUTH2_PASSWORD",
                "OAUTH2_AUTH_CODE",
                "OAUTH2_AUTH_IMPLICIT",
                "OPEN_ID_CONNECT",
                name="securityscheme",
            ),
            nullable=True,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("excluded_functions", postgresql.ARRAY(sa.UUID()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", "app_id", name="uc_integration_composite_key"),
        sa.UniqueConstraint("project_id", "app_id", name="uc_project_app"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "DISABLED", "DELETED", name="apikeystatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "linked_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_app_integration_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=False),
        sa.Column(
            "security_scheme",
            sa.Enum(
                "API_KEY",
                "HTTP_BASIC",
                "HTTP_BEARER",
                "OAUTH2_PASSWORD",
                "OAUTH2_AUTH_CODE",
                "OAUTH2_AUTH_IMPLICIT",
                "OPEN_ID_CONNECT",
                name="securityscheme",
            ),
            nullable=True,
        ),
        sa.Column("security_credentials", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["apps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_app_integration_id", "project_id", "app_id"],
            [
                "project_app_integrations.id",
                "project_app_integrations.project_id",
                "project_app_integrations.app_id",
            ],
            name="fk_linked_account_project_app_integration",
        ),
        sa.ForeignKeyConstraint(
            ["project_app_integration_id"],
            ["project_app_integrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_app_integration_id", "account_name", name="uc_integration_id_account_name"
        ),
        sa.UniqueConstraint(
            "project_id", "app_id", "account_name", name="uc_project_id_app_id_account_name"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linked_accounts")
    op.drop_table("api_keys")
    op.drop_table("project_app_integrations")
    op.drop_table("agents")
    op.drop_table("projects")
    op.drop_table("functions")
    op.drop_table("users")
    op.drop_table("organizations")
    op.drop_table("apps")
    # ### end Alembic commands ###

    # Drop the Enum types
    op_bind = op.get_bind()
    sa.Enum(
        "PUBLIC",
        "PRIVATE",
        name="visibility",
    ).drop(op_bind)
    sa.Enum(
        "ACTIVE",
        "DISABLED",
        "DELETED",
        name="status",
    ).drop(op_bind)
    sa.Enum(
        "REST",
        name="protocol",
    ).drop(op_bind)
    sa.Enum(
        "CUSTOM",
        "FREE",
        "PRO",
        "ENTERPRISE",
        name="plan",
    ).drop(op_bind)
    sa.Enum(
        "API_KEY",
        "HTTP_BASIC",
        "HTTP_BEARER",
        "OAUTH2_PASSWORD",
        "OAUTH2_AUTH_CODE",
        "OAUTH2_AUTH_IMPLICIT",
        "OPEN_ID_CONNECT",
        name="securityschemetype",
    ).drop(op_bind)
    # drop extentions
    op.execute("DROP EXTENSION IF EXISTS vector;")
